---
- name: Edit postgresql config
  ansible.builtin.lineinfile:
    path: "/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf"
    regexp: "shared_preload_libraries ="
    line: "shared_preload_libraries = 'pg_strom'"
  notify: Restart postgresql

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Create extension
  community.postgresql.postgresql_ext:
    db: "{{ item }}"
    name: pg_strom
    state: present
  with_items: "{{ postgresql_pg_strom_databases }}"
  become: true
  become_user: "{{ _postgresql_user }}"
